//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int ChildId { get; set; }
        public string Full_Name { get; set; }
        public Nullable<System.DateTime> BornDate { get; set; }
        public string Tz { get; set; }
        public int ParentId { get; set; }
    
        public virtual User User { get; set; }
    }
}
